# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6094pF0kLC_A8RcNyiyjX6CcQzi3rxx
"""

from fastapi import FastAPI
import uvicorn

# Import routers
from user import router as user_router
from chat import router as chat_router
from question import router as question_router

app = FastAPI(title="Study API", version="1.0")

# Health check
@app.get("/")
def health_check():
    return {"status": "ok", "message": "All routers are working 🚀"}

# Register routers
app.include_router(user_router)
app.include_router(chat_router)
app.include_router(question_router)

if __name__ == "__main__":
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)