# -*- coding: utf-8 -*-
"""question.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6094pF0kLC_A8RcNyiyjX6CcQzi3rxx
"""

from fastapi import APIRouter
from pymongo import MongoClient
from bson import ObjectId
from datetime import datetime
import requests

# MongoDB setup (hardcoded)
MONGO_URI = "mongodb+srv://chatpdfxai_db_user:esfmQRoJQZpJ7if3@cluster0.xzatb0d.mongodb.net/chatpdf?retryWrites=true&w=majority&appName=Cluster0"
client = MongoClient(MONGO_URI)
db = client["chatpdf"]
chats_collection = db["chats"]

# Gemini config (hardcoded)
GEMINI_API_KEY = "AIzaSyAYzx76osJSXZd61P15YHFbByolJ0j0Xo8"
MODEL_NAME = "gemini-2.5-flash"
GEMINI_API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL_NAME}:generateContent"

router = APIRouter(prefix="/question", tags=["question"])

@router.get("/ask")
def ask_question(chat_id: str, question: str, onlycontext: bool = True):
    chat = chats_collection.find_one({"_id": ObjectId(chat_id)})
    if not chat:
        return {"status": "no_answer", "answer": "Chat not found ❌"}

    context = chat["context"]

    if onlycontext:
        instruction = """
        You are a strict but supportive study assistant 📘🧠.
        RULES:
        • Answer ONLY from CONTEXT. If not found, reply exactly:
          "❌ Sorry, I couldn’t find anything related in your uploads."
        • Reply in the SAME LANGUAGE as the QUESTION.
        • Format answers:
          1. Key Concepts 🌱
          2. Definitions 📘
          3. Examples 💡
          4. Summary 🎯
        """
    else:
        instruction = """
        You are a helpful study assistant 📘🧠.
        RULES:
        • Use CONTEXT as main source, small extra clarifications allowed.
        • Reply in the SAME LANGUAGE as the QUESTION.
        • Format answers:
          1. Key Concepts 🌱
          2. Definitions 📘
          3. Examples 💡
          4. Summary 🎯
        """

    user_prompt = f"""
    {instruction}

    CONTEXT:
    {context}

    QUESTION:
    {question}
    """

    payload = {"contents": [{"role": "user", "parts": [{"text": user_prompt}]}]}
    headers = {"Content-Type": "application/json", "x-goog-api-key": GEMINI_API_KEY}

    try:
        response = requests.post(GEMINI_API_URL, json=payload, headers=headers, timeout=60)
        response.raise_for_status()
        data = response.json()

        if "candidates" in data and len(data["candidates"]) > 0:
            answer = data["candidates"][0]["content"]["parts"][0]["text"].strip()
        else:
            answer = "❌ Sorry, I couldn’t find anything related."

        # Save user Q and Gemini A in chat history
        chats_collection.update_one(
            {"_id": ObjectId(chat_id)},
            {"$push": {"messages": {"role": "user", "text": question, "timestamp": datetime.utcnow().isoformat()}}}
        )
        chats_collection.update_one(
            {"_id": ObjectId(chat_id)},
            {"$push": {"messages": {"role": "assistant", "text": answer, "timestamp": datetime.utcnow().isoformat()}}}
        )

        return {
            "status": "answer" if not answer.startswith("❌") else "no_answer",
            "answer": None if answer.startswith("❌") else answer,
        }
    except Exception as e:
        return {"status": "no_answer", "answer": f"API error: {str(e)}"}